DECLARE
   a_ VARCHAR2(32000) := NULL; --info
   b_ VARCHAR2(32000) := 'MDMGT'; --module
   c_ VARCHAR2(32000) := 'Core'; --layerId
   d_ VARCHAR2(32000) := '!
$PO=!frmMdmBasicData
-$DESCRIPTION=MDM Basic Data
-$DEP_OBJECTS=!
--$DEP_OBJECT=!tbwSourceMap
---$TYPE=3
---
--$DEP_OBJECT=!tbwMethodList
---$TYPE=3
---
--
-$SEC_OBJECTS=!
--$SEC_OBJECT=!MDM_BASIC_DATA_HEADER
---$TYPE=VIEW
---$SUB_TYPE=3
---
--$SEC_OBJECT=!MDM_BASIC_DATA_HEADER_API.New__
---$TYPE=METHOD
---$SUB_TYPE=1
---
--$SEC_OBJECT=!MDM_BASIC_DATA_HEADER_API.Modify__
---$TYPE=METHOD
---$SUB_TYPE=1
---
--$SEC_OBJECT=!MDM_BASIC_DATA_HEADER_API.Remove__
---$TYPE=METHOD
---$SUB_TYPE=1
---
--$SEC_OBJECT=!APPROVAL_PROFILE
---$TYPE=VIEW
---$SUB_TYPE=5
---
--$SEC_OBJECT=!mdm_basic_data_header_api.C_Create_New_Revis_Struct
---$TYPE=METHOD
---$SUB_TYPE=2
---
--
-
$PO=!tbwSourceMap
-$DESCRIPTION=Source Mapping
-$DEP_OBJECTS=!
--
-$SEC_OBJECTS=!
--$SEC_OBJECT=!MDM_SOURCE_MAP
---$TYPE=VIEW
---$SUB_TYPE=3
---
--$SEC_OBJECT=!MDM_SOURCE_MAP_API.New__
---$TYPE=METHOD
---$SUB_TYPE=1
---
--$SEC_OBJECT=!MDM_SOURCE_MAP_API.Modify__
---$TYPE=METHOD
---$SUB_TYPE=1
---
--$SEC_OBJECT=!MDM_SOURCE_MAP_API.Remove__
---$TYPE=METHOD
---$SUB_TYPE=1
---
--$SEC_OBJECT=!MDM_BASIC_DATA_HEADER
---$TYPE=VIEW
---$SUB_TYPE=5
---
--
-
$PO=!tbwMethodList
-$DESCRIPTION=Method List
-$DEP_OBJECTS=!
--
-$SEC_OBJECTS=!
--$SEC_OBJECT=!MDM_METHOD_LIST
---$TYPE=VIEW
---$SUB_TYPE=3
---
--$SEC_OBJECT=!MDM_METHOD_LIST_API.New__
---$TYPE=METHOD
---$SUB_TYPE=1
---
--$SEC_OBJECT=!MDM_METHOD_LIST_API.Modify__
---$TYPE=METHOD
---$SUB_TYPE=1
---
--$SEC_OBJECT=!MDM_METHOD_LIST_API.Remove__
---$TYPE=METHOD
---$SUB_TYPE=1
---
--$SEC_OBJECT=!INTFACE_VIEWS
---$TYPE=VIEW
---$SUB_TYPE=5
---
--$SEC_OBJECT=!MDM_BASIC_DATA_HEADER
---$TYPE=VIEW
---$SUB_TYPE=5
---
--
-
$PO=!frmMdmRequestHeader
-$DESCRIPTION=MDM Request 
-$DEP_OBJECTS=!
--$DEP_OBJECT=!tbwGeneral
---$TYPE=3
---
--$DEP_OBJECT=!tbwDataValues
---$TYPE=3
---
--
-$SEC_OBJECTS=!
--$SEC_OBJECT=!MDM_REQUEST_HEADER
---$TYPE=VIEW
---$SUB_TYPE=3
---
--$SEC_OBJECT=!MDM_REQUEST_HEADER_API.New__
---$TYPE=METHOD
---$SUB_TYPE=1
---
--$SEC_OBJECT=!MDM_REQUEST_HEADER_API.Modify__
---$TYPE=METHOD
---$SUB_TYPE=1
---
--$SEC_OBJECT=!MDM_REQUEST_HEADER_API.Remove__
---$TYPE=METHOD
---$SUB_TYPE=1
---
--$SEC_OBJECT=!MDM_BASIC_DATA_HEADER
---$TYPE=VIEW
---$SUB_TYPE=5
---
--
-
$PO=!tbwGeneral
-$DESCRIPTION=General
-$DEP_OBJECTS=!
--
-$SEC_OBJECTS=!
--$SEC_OBJECT=!MDM_GENERAL
---$TYPE=VIEW
---$SUB_TYPE=3
---
--$SEC_OBJECT=!MDM_SOURCE_MAP_API.New__
---$TYPE=METHOD
---$SUB_TYPE=1
---
--$SEC_OBJECT=!MDM_SOURCE_MAP_API.Modify__
---$TYPE=METHOD
---$SUB_TYPE=1
---
--$SEC_OBJECT=!MDM_SOURCE_MAP_API.Remove__
---$TYPE=METHOD
---$SUB_TYPE=1
---
--$SEC_OBJECT=!MDM_BASIC_DATA_HEADER
---$TYPE=VIEW
---$SUB_TYPE=5
---
--
-
$PO=!tbwDataValues
-$DESCRIPTION=Data Values
-$DEP_OBJECTS=!
--
-$SEC_OBJECTS=!
--
-
'; --poMsg
BEGIN

   
IFSAPP.PRES_OBJECT_UTIL_API.TRANSFER_TO_BUILD(:info, :module, :layerId, :poMsg);
a_  := 'MDMGT'; --info
b_ := 'MDMGT'; --module
c_  := 'Core'; --layerId
IFSAPP.PRES_OBJECT_UTIL_API.TRANSFER_BUILD_TO_LIVE(:info, :module, :layerId);
COMMIT;
END;
